// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@smartschedule.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/private/calendar/connections": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Trả về tất cả các lịch đã kết nối của người dùng hiện tại",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "Lấy danh sách kết nối lịch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CalendarConnectionListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/private/calendar/events": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo sự kiện mới trên Google Calendar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "Tạo sự kiện lịch",
                "parameters": [
                    {
                        "description": "Thông tin sự kiện",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-api-starter_modules_calendar_dto.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/private/calendar/suggested-slots": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tìm các khung giờ mà tất cả người tham gia đều rảnh",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "Tìm khung giờ rảnh",
                "parameters": [
                    {
                        "description": "Yêu cầu tìm khung giờ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SuggestedSlotsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuggestedSlotsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/private/invitations/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Trả về danh sách các lời mời sự kiện đang chờ người dùng xác nhận",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invitation"
                ],
                "summary": "Lấy lời mời chờ duyệt",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.InvitationResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/private/invitations/pending/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Trả về số lượng lời mời đang chờ xác nhận",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invitation"
                ],
                "summary": "Đếm số lời mời chờ duyệt",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/private/invitations/{id}/accept": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xác nhận tham gia sự kiện và thêm vào lịch Google",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invitation"
                ],
                "summary": "Chấp nhận lời mời",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invitation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.InvitationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/private/invitations/{id}/decline": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Từ chối tham gia sự kiện",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invitation"
                ],
                "summary": "Từ chối lời mời",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invitation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CalendarConnectionListResponse": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CalendarConnectionResponse"
                    }
                }
            }
        },
        "dto.CalendarConnectionResponse": {
            "type": "object",
            "properties": {
                "calendar_email": {
                    "type": "string"
                },
                "connected_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "dto.CreateEventResponse": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "event_id": {
                    "type": "string"
                },
                "meeting_link": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.DisconnectedUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.EventDataDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "meeting_link": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.InvitationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator_id": {
                    "type": "string"
                },
                "event_data": {
                    "$ref": "#/definitions/dto.EventDataDTO"
                },
                "event_google_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.SuggestedSlot": {
            "type": "object",
            "properties": {
                "available_count": {
                    "type": "integer"
                },
                "end_time": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "score": {
                    "description": "0-100 based on availability",
                    "type": "integer"
                },
                "start_time": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "dto.SuggestedSlotsRequest": {
            "type": "object",
            "properties": {
                "days_ahead": {
                    "description": "default 7",
                    "type": "integer"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "start_date": {
                    "description": "optional, RFC3339 date (YYYY-MM-DD)",
                    "type": "string"
                },
                "time_preference": {
                    "description": "\"morning\", \"afternoon\", \"evening\", \"\" for no preference",
                    "type": "string"
                },
                "user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "working_hours_only": {
                    "description": "8:00-18:00",
                    "type": "boolean"
                }
            }
        },
        "dto.SuggestedSlotsResponse": {
            "type": "object",
            "properties": {
                "connected_count": {
                    "type": "integer"
                },
                "disconnected_count": {
                    "type": "integer"
                },
                "disconnected_users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DisconnectedUser"
                    }
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SuggestedSlot"
                    }
                },
                "total_participants": {
                    "type": "integer"
                },
                "warning": {
                    "type": "string"
                }
            }
        },
        "errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/errors.ErrorCode"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "errors.ErrorCode": {
            "type": "integer",
            "enum": [
                1000,
                1001,
                1002,
                1003,
                1004,
                1005,
                2006,
                2007,
                2008,
                2009,
                2010,
                3011,
                3012,
                3013,
                3014,
                3015,
                3016,
                3017,
                3018,
                3019,
                3020,
                3021,
                4022,
                4023,
                4024,
                4025,
                5026,
                5027,
                5028,
                5029,
                6030,
                6031,
                6032,
                6033,
                7034,
                7035
            ],
            "x-enum-varnames": [
                "ErrInvalidCredentials",
                "ErrTokenExpired",
                "ErrUnauthorized",
                "ErrForbidden",
                "ErrMissingAuthorizationHeader",
                "ErrInvalidTokenFormat",
                "ErrInvalidInput",
                "ErrInvalidEmail",
                "ErrInvalidPassword",
                "ErrInvalidFormat",
                "ErrInvalidRequestData",
                "ErrNotFound",
                "ErrAlreadyExists",
                "ErrResourceLocked",
                "ErrResourceExpired",
                "ErrCreateFailed",
                "ErrGetFailed",
                "ErrInvalidSlug",
                "ErrDuplicateSlug",
                "ErrInvalidParent",
                "ErrUpdateFailed",
                "ErrDeleteFailed",
                "ErrDatabase",
                "ErrDatabaseTimeout",
                "ErrUniqueViolation",
                "ErrForeignKey",
                "ErrBusinessRule",
                "ErrInvalidState",
                "ErrLimitExceeded",
                "ErrOperationFailed",
                "ErrInternalServer",
                "ErrConfiguration",
                "ErrThirdParty",
                "ErrNetwork",
                "ErrUploadToR2",
                "ErrSaveStorageDb"
            ]
        },
        "go-api-starter_modules_calendar_dto.CreateEventRequest": {
            "type": "object",
            "required": [
                "end_time",
                "start_time",
                "title"
            ],
            "properties": {
                "attendees": {
                    "description": "Email addresses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "meeting_link": {
                    "type": "string"
                },
                "start_time": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7070",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SmartSchedule API",
	Description:      "API Backend cho ứng dụng SmartSchedule - Lịch hẹn thông minh",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
